project:
  type: website
  preview:
    port: 4900 
website:
  title: "kurianbenoy"
  navbar:
    right:
      - about.qmd
      - text: "Blog"
        href: blog.html
      - text: "Talks"
        href: talks.html
      - icon: github
        href: https://github.com/kurianbenoy
      - icon: twitter
        href: https://twitter.com/kurianbenoy2
      - icon: rss
        href: blog.xml
format:
  html:
    theme: sketchy 
    css: styles.css



