project:
  type: website
  output-dir: docs
  preview:
    port: 4900 
website:
  title: "kurianbenoy"
  navbar:
    right:
      - text: "Blog"
        href: blog.html
      - text: "Talks"
        href: talks.html
      - icon: github
        href: https://github.com/kurianbenoy
      - icon: twitter
        href: https://twitter.com/kurianbenoy2
      - text: "TIL"
        href: https://til.kurianbenoy.com/
      - icon: rss
        href: blog.xml
format:
  html:
    theme:
    - sketchy
    - custom.scss
    css: styles.css




